language: generic
dist: trusty
sudo: required

matrix:
  include:
    - env: CUDA=6.5-19
    - env: CUDA=7.0-28
    - env: CUDA=7.5-18
    - env: CUDA=8.0.61-1

before_install:
  ##### INSTALL CMAKE 3.11.3 #####
  - echo "Installing CMAKE"
  - wget https://cmake.org/files/v3.11/cmake-3.11.3-Linux-x86_64.sh
  - sudo sh cmake-3.11.3-Linux-x86_64.sh --prefix=/home/travis/.local/ --exclude-subdir
  ##### INSTALL CUDA #####
  - echo "Installing CUDA library"
  - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_${CUDA}_amd64.deb
  - sudo dpkg -i cuda-repo-ubuntu1404_${CUDA}_amd64.deb
  - sudo apt-get update -qq
  - export CUDA_APT=${CUDA:0:3}
  - export CUDA_APT=${CUDA_APT/./-}
  - sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT} cuda-cufft-dev-${CUDA_APT} cuda-cublas-dev-${CUDA_APT}
  - sudo apt-get clean
  - export CUDA_HOME=/usr/local/cuda-${CUDA:0:3}
  - export LD_LIBRARY_PATH=${CUDA_HOME}/nvvm/lib64:${LD_LIBRARY_PATH}
  - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - export PATH=${CUDA_HOME}/bin:${PATH}

install:
  - nvcc --version
  - gcc --version
  - g++ --version

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

after_failure:
  - dmesg
  - ls -R /usr/local/cuda*
