# https://github.com/gpuopenanalytics/libgdf/blob/master/travisci/install-cuda-trusty.sh
# https://github.com/gpuopenanalytics/libgdf/blob/master/.travis.yml

# https://github.com/JuliaGPU/CUDAapi.jl/blob/master/.travis.yml
# https://github.com/JuliaGPU/CUDAapi.jl/blob/master/.travis.osx
# https://github.com/JuliaGPU/CUDAapi.jl/blob/master/.travis.linux

# https://github.com/tmcdonell/travis-scripts/blob/master/install-cuda-trusty.sh

language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      env: CUDA=6.5-19
    - os: linux
      dist: trusty
      env: CUDA=7.0-28
    - os: linux
      dist: trusty
      env: CUDA=7.5-18
    - os: linux
      dist: xenial
      env: CUDA=8.0.61-1
    - os: linux
      dist: xenial
      env: CUDA=9.0.176-1
    - os: linux
      dist: xenial
      env: CUDA=9.1.85-1
    - os: linux
      dist: xenial
      env: CUDA=9.2.148-1
    - os: linux
      dist: xenial
      env: CUDA=10.0.130-1
    - os : osx
      osx_image: xcode7.3
      env: CUDA=7.5.27
      before_install:  &cuda_install
        - brew update
        - brew upgrade cmake
        - brew install libomp
        - source ./scripts/travis_osx
    - os : osx
      osx_image: xcode8
      env: CUDA=8.0.61
      before_install: *cuda_install
    - os : osx
      osx_image: xcode8.3
      env: CUDA=9.0.176
      before_install: *cuda_install
    - os : osx
      osx_image: xcode9.2
      env: CUDA=9.1.128
      before_install: *cuda_install
    - os : osx
      osx_image: xcode9.2
      env: CUDA=9.2.148
      before_install: *cuda_install
    - os : osx
      osx_image: xcode9.4
      env: CUDA=10.0.130
      before_install: *cuda_install

    # SONARCLOUD
    - os: linux
      dist: xenial
      addons:
        sonarcloud:
          organization: "zialus-github"
          token:
            secure: "aHTVrZn6eFrAw+3BSmvHQiSmHtMosYpiBRr3NetWPUdXUUVvEH21TogII75+Bg9ZP7VLKxcfRnMPWJnnAYUaOjd0GIn4LV/76Mxf/LcLVx6nWEgs+j8KiK3Y96ujniCFxLzV6gTQaIW+IFWVOhX5Vkf+NcN94EM1MuhHOqCHtJKx6pli1zDhApxXQcLYsytMKxzXrLBK8A+Akiw85vcSb2Pql8kCTECilOpAV5CQwfB4ORXyIYC6KzXtzbZiiPce51Z/hiyAydeJdEBUeGQrvarR9hj+X7dlDa0fPQZQDVFWl0aPDTe8BYXHnTkaTxtZoqtDsdyZ8+HGiZ8JBD7o9bla6P9gvf+GP1eW5D4H2rNK57caZyC38kdwm3e3VXGK6D8SusYCyG75ep5Peuz1XDoykMI/dFkZyfESI+yyIkgDBjw+V+u7m+b9AsgLmtHOa+hJXUeHZPDiVlTDv26OHqxgIDq7nA5k/9/mekp6eiJSqzH74TtsZGaIXGrnXuZbbR02i+64V+nLYQZaruQEyZQGZEcRBsX2gQBEpCJyWYYj0yFeen/jnaL7QeCBQbRFIC1aDHdRByrn1nYpsVS9dEt95plKAia+T2ZUZ3TPZ/3yCJZhZdUFBhsXbCo2HNfirqYYKN6Apg3CEqVzpi21ksb+39LmyTdFa2GXAo8Eaak="
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
        - ctest -V -C Release
        - cd ..
        - sonar-scanner
      env:
        - SONAR_CLOUD="YUP"
        - CUDA=10.0.130-1

before_install:
  - wget https://cmake.org/files/v3.13/cmake-3.13.2-Linux-x86_64.sh
  - sudo sh cmake-3.13.2-Linux-x86_64.sh --prefix=/home/travis/.local/ --exclude-subdir
  - source ./scripts/travis_linux

install:
  - export CUDA_HOME=/usr/local/cuda
  - export PATH=${CUDA_HOME}/bin:${PATH}
  - nvcc --version
  - gcc --version
  - g++ --version

script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j2

after_failure:
  - dmesg
  - ls -R /usr/local/cuda*
